force-app/main/default/objects/Claim_Event_Log__c/Claim_Event_Log__c.object-meta.xml
<CustomObject>
    <label>Claim Event Log</label>
    <nameField>
        <displayFormat>CE-{00000}</displayFormat>
        <label>Claim Event Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Event Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim_Event_Log__c/fields/EventSubType__c.field-meta.xml
<CustomField>
    <fullName>EventSubType__c</fullName>
    <label>Event Sub Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim_Event_Log__c/fields/EventType__c.field-meta.xml
<CustomField>
    <fullName>EventType__c</fullName>
    <label>Event Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim_Event_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Not Yet Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cve__BenefitClaimed__c/cve__BenefitClaimed__c.object-meta.xml
<CustomObject>
    <customHelpPage>cve__BenefitClaimedHelp</customHelpPage>
    <label>Benefit Claimed</label>
    <nameField>
        <displayFormat>BC-{YYYY}-{000000}</displayFormat>
        <label>Benefit Claimed Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefits Claimed</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/cve__BenefitClaimed__c/fields/cve__Benefit__c.field-meta.xml
<CustomField>
    <fullName>cve__Benefit__c</fullName>
    <label>Benefit</label>
    <referenceTo>cve__Benefit__c</referenceTo>
    <relationshipLabel>Benefits Claimed</relationshipLabel>
    <relationshipName>BenefitClaimeds</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/cve__BenefitClaimed__c/fields/cve__Claim__c.field-meta.xml
<CustomField>
    <fullName>cve__Claim__c</fullName>
    <label>Claim</label>
    <referenceTo>cve__Claim__c</referenceTo>
    <relationshipLabel>Benefits Claimed</relationshipLabel>
    <relationshipName>BenefitClaimeds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/cve__BenefitClaimed__c/fields/cve__ClaimantInsuredAccount__c.field-meta.xml
<CustomField>
    <fullName>cve__ClaimantInsuredAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claimant/Insured Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Benefits Claimed</relationshipLabel>
    <relationshipName>BenefitsClaimed</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cve__BenefitClaimed__c/fields/cve__Policy__c.field-meta.xml
<CustomField>
    <fullName>cve__Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>cve__Policy__c</referenceTo>
    <relationshipLabel>Benefits Claimed</relationshipLabel>
    <relationshipName>BenefitClaimeds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cve__BenefitClaimed__c/fields/cve__Status__c.field-meta.xml
<CustomField>
    <fullName>cve__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Appeal</fullName>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Approval Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cve__Claim__c/cve__Claim__c.object-meta.xml
<CustomObject>
    <customHelpPage>cve__ClaimHelp</customHelpPage>
    <label>Claim</label>
    <nameField>
        <displayFormat>C-{YYYY}-{000000}</displayFormat>
        <label>Claim Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cve__Claim__c/fields/ClaimEventLogTrigger__c.field-meta.xml
<CustomField>
    <fullName>ClaimEventLogTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ClaimEventLogTrigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cve__Claim__c/fields/cve__ClaimantInsuredAccount__c.field-meta.xml
<CustomField>
    <fullName>cve__ClaimantInsuredAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claimant/Insured Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cve__Claim__c/fields/cve__Policy__c.field-meta.xml
<CustomField>
    <fullName>cve__Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>cve__Policy__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cve__Claim__c/fields/cve__PolicyNames__c.field-meta.xml
<CustomField>
    <fullName>cve__PolicyNames__c</fullName>
    <description>This will displays Policy names that are associated with Benefit Claimed of the Claim</description>
    <label>Policy Names</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cve__Claim__c/fields/cve__Status__c.field-meta.xml
<CustomField>
    <fullName>cve__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delegated_Claim_Task__c/Delegated_Claim_Task__c.object-meta.xml
<CustomObject>
    <label>Delegated Claim Task</label>
    <nameField>
        <label>Delegated Claim Tasks Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delegated Claim Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delegated_Claim_Task__c/fields/BenefitClaimed__c.field-meta.xml
<CustomField>
    <fullName>BenefitClaimed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Benefit Claimed</label>
    <referenceTo>cve__BenefitClaimed__c</referenceTo>
    <relationshipLabel>Benefit Claimed</relationshipLabel>
    <relationshipName>BenefitClaimeds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delegated_Claim_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClaimTriggerHelper.cls
public with sharing class ClaimTriggerHelper 
{
    public static void callOutClaim(List<cve__Claim__c> claimList, Map<Id, cve__Claim__c> claimOldMAP)
    {
        Set<String> claimId = new Set<String>();
        List<Mainwrapper.ClaimContext> contextList = new List<Mainwrapper.ClaimContext>();
        Set<Mainwrapper.ClaimContext> contextSet = new Set<Mainwrapper.ClaimContext>();
        List<Mainwrapper.PolicyContext> policyList =  new List<Mainwrapper.PolicyContext> ();
        Mainwrapper.EventContext event = new Mainwrapper.EventContext();
        Set<String> policyNamesSet = new Set<String>();
        if(claimList != Null )
        {
            for(cve__Claim__c claimObj : claimList)
            {
                if(!claimObj.ClaimEventLogTrigger__c && claimOldMAP != null)
                { 
                    if(claimOldMAP.get(ClaimObj.Id).cve__Status__c != ClaimObj.cve__Status__c && ClaimObj.cve__Status__c == 'Open')
                    {
                        claimId.add(claimObj.Id);
                    }
                }
            }
        }
        if(claimId != null)
        {
            for(cve__Claim__c claim : [Select cve__ClaimantInsuredAccount__c, cve__ClaimantInsuredAccount__r.Name, cve__ClaimantInsuredAccount__r.cve_Sanlam_Member_ID__c ,cve__ClaimantInsuredAccount__r.recordTypeId, cve__ClaimantInsuredAccount__r.recordType.Name, cve__PolicyNames__c From cve__Claim__c Where Id IN :claimId])
            {
                Mainwrapper.ClaimContext context = new Mainwrapper.ClaimContext();
                context.accountId = claim.cve__ClaimantInsuredAccount__c;
                context.accountName = claim.cve__ClaimantInsuredAccount__r.Name;
                context.sanlamMemberNumber = claim.cve__ClaimantInsuredAccount__r.cve_Sanlam_Member_ID__c;
                context.recordTypeId = claim.cve__ClaimantInsuredAccount__r.recordTypeId;
                context.recordTypeName = 'personRecord'; //claim.cve__ClaimantInsuredAccount__r.recordType.Name;
                //context.effectiveDate =  '2022-03-01T01:00:00.1234567+02:00';
                contextSet.add(context);
            }
        } 
        Set<String> policyIds = new Set<String>();
        for(cve__BenefitClaimed__c bcClaim : [Select cve__Policy__c From cve__BenefitClaimed__c Where cve__Claim__c IN :claimId]){
            policyIds.add(bcClaim.cve__Policy__c);
        }
        
        List<cve__Policy__c> listPolicy = [Select Id, Name , (SELECT Id, Name, cve__Claim__c, cve__Benefit__c, cve__Policy__c 
                                                              FROM cve__BenefitClaimeds__r where cve__Claim__c IN : claimId) from cve__Policy__c WHERE Id In : policyIds];
        for(cve__Policy__c policyObj : listPolicy)
        {
            List<Mainwrapper.Benefits> benefitList = new List<Mainwrapper.Benefits>();
            Mainwrapper.PolicyContext policy  = new Mainwrapper.PolicyContext();
            policy.policyId = policyObj.Id;
            policy.policyName = policyObj.Name;
            for(cve__BenefitClaimed__c bcClaim : policyObj.cve__BenefitClaimeds__r)
            {
                Mainwrapper.Benefits benefit = new Mainwrapper.Benefits();
                benefit.benefitId = bcClaim.cve__Benefit__c;
                benefit.benefitClaimedId = bcClaim.Id;
                benefit.benefitClaimedNumber= bcClaim.Name;  
                benefitList.add(benefit);
            }
            policy.Benefits = benefitList;
            policyList.add(policy);
        }
        Mainwrapper.ClaimMangement claim = new Mainwrapper.ClaimMangement();
        if(!contextSet.isEmpty() && contextSet.size()> 0 && !policyList.isEmpty() && policyList.size()> 0 && event != null)
        {
            Claim_Event_Log__c obj = claimEventLog();
            event.eventId =  obj.Id;
            event.userId = userinfo.getuserid();                                                 
            event.userName = userinfo.getName();
            
            List<cve__Claim__c> claimUpdate =new  List<cve__Claim__c>();
            for(cve__Claim__c claimObj : claimList){
                cve__Claim__c claimObject = new cve__Claim__c();
                claimObject.Id = claimObj.Id;
                claimObject.ClaimEventLogTrigger__c =True;
                claimUpdate.add(claimObject);
            }
            if(claimUpdate !=Null){
                try{
                    update claimUpdate;
                } catch(Exception ex){
                }
            }
            contextList.addAll(contextSet);
            claim.claimEventType = 'createClaim';
            claim.eventContext = event;
            claim.claimContext = contextList;
            claim.policyContext = policyList; 
            makeCreateClaimCallout(JSON.serialize(claim));
        }
    }
    private static Claim_Event_Log__c claimEventLog()
    {
        Claim_Event_Log__c eve = new Claim_Event_Log__c();
        eve.EventType__c = '';
        eve.EventSubType__c = '';
        eve.Status__c = 'Not Yet Started';
        try{
            insert eve;
        } catch(Exception ex){
            
        }
        return eve;
    }
    @Future(callout=true)
    public static void makeCreateClaimCallout(String claim){
        Mainwrapper.ClaimMangement ClaimMangementobj = ( Mainwrapper.ClaimMangement) JSON.deserialize(claim,  Mainwrapper.ClaimMangement.class); 
        ClaimEventType.createContext(ClaimMangementobj);
    }
    
    public static void finaliseClaimEvent(List<cve__Claim__c> claimList, Map<Id, cve__Claim__c> claimOldMAP){
        Set<String> claimId = new Set<String>();
        List<Mainwrapper.ClaimContext> contextList = new List<Mainwrapper.ClaimContext>();
        Set<Mainwrapper.ClaimContext> contextSet = new Set<Mainwrapper.ClaimContext>();
        List<Mainwrapper.PolicyContext> policyList =  new List<Mainwrapper.PolicyContext> ();
        Mainwrapper.EventContext event = new Mainwrapper.EventContext();
        Set<String> policyNamesSet = new Set<String>();
        if(claimList != Null )
        { system.debug('claimOldMAP : '+claimOldMAP);
            for(cve__Claim__c claimObj : claimList)
            {
                if(claimOldMAP != null)
                { 
                    if(claimOldMAP.get(ClaimObj.Id).cve__Status__c != ClaimObj.cve__Status__c && ClaimObj.cve__Status__c == 'Closed')
                    {
                        claimId.add(claimObj.Id);
                    }
                }
            }
        }
        if(claimId != null)
        {
            for(cve__Claim__c claim : [Select cve__ClaimantInsuredAccount__c, cve__ClaimantInsuredAccount__r.Name, cve__ClaimantInsuredAccount__r.cve_Sanlam_Member_ID__c ,cve__ClaimantInsuredAccount__r.recordTypeId, cve__ClaimantInsuredAccount__r.recordType.Name, cve__PolicyNames__c From cve__Claim__c Where Id IN :claimId])
            {
                Mainwrapper.ClaimContext context = new Mainwrapper.ClaimContext();
                context.accountId = claim.cve__ClaimantInsuredAccount__c;
                context.accountName = claim.cve__ClaimantInsuredAccount__r.Name;
                context.sanlamMemberNumber = claim.cve__ClaimantInsuredAccount__r.cve_Sanlam_Member_ID__c;
                context.recordTypeId = claim.cve__ClaimantInsuredAccount__r.recordTypeId;
                context.recordTypeName = 'personRecord'; //claim.cve__ClaimantInsuredAccount__r.recordType.Name;
                //context.effectiveDate =  '2022-03-01T01:00:00.1234567+02:00';
                contextSet.add(context);
            }
        } 
        Set<String> policyIds = new Set<String>();
        for(cve__BenefitClaimed__c bcClaim : [Select cve__Policy__c From cve__BenefitClaimed__c Where cve__Claim__c IN :claimId]){
            policyIds.add(bcClaim.cve__Policy__c);
        }
        
        List<cve__Policy__c> listPolicy = [Select Id, Name , (SELECT Id, Name, cve__Claim__c, cve__Benefit__c, cve__Policy__c 
                                                              FROM cve__BenefitClaimeds__r where cve__Claim__c IN : claimId) from cve__Policy__c WHERE Id In : policyIds];
        for(cve__Policy__c policyObj : listPolicy)
        {
            List<Mainwrapper.Benefits> benefitList = new List<Mainwrapper.Benefits>();
            Mainwrapper.PolicyContext policy  = new Mainwrapper.PolicyContext();
            policy.policyId = policyObj.Id;
            policy.policyName = policyObj.Name;
            for(cve__BenefitClaimed__c bcClaim : policyObj.cve__BenefitClaimeds__r)
            {
                Mainwrapper.Benefits benefit = new Mainwrapper.Benefits();
                benefit.benefitId = bcClaim.cve__Benefit__c;
                benefit.benefitClaimedId = bcClaim.Id;
                benefit.benefitClaimedNumber= bcClaim.Name;  
                benefitList.add(benefit);
            }
            policy.Benefits = benefitList;
            policyList.add(policy);
        }
        Mainwrapper.ClaimMangement claim = new Mainwrapper.ClaimMangement();
        if(!contextSet.isEmpty() && contextSet.size()> 0 && !policyList.isEmpty() && policyList.size()> 0 && event != null)
        {
            Claim_Event_Log__c obj = claimEventLog();
            event.eventId =  obj.Id;
            event.userId = userinfo.getuserid();                                                 
            event.userName = userinfo.getName();
            
          
            contextList.addAll(contextSet);
            claim.claimEventType = 'finaliseClaim';
            claim.eventContext = event;
            claim.claimContext = contextList;
            claim.policyContext = policyList; 
            makeCreateClaimCallout(JSON.serialize(claim));
        }
    }
    
}