force-app/main/default/objects/cve__BenefitClaimed__c/cve__BenefitClaimed__c.object-meta.xml
<CustomObject>
    <customHelpPage>cve__BenefitClaimedHelp</customHelpPage>
    <label>Benefit Claimed</label>
    <nameField>
        <displayFormat>BC-{YYYY}-{000000}</displayFormat>
        <label>Benefit Claimed Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefits Claimed</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/cve__BenefitClaimed__c/fields/Benefit_code__c.field-meta.xml
<CustomField>
    <fullName>Benefit_code__c</fullName>
    <label>Benefit code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cve__BenefitClaimed__c/fields/cve__Benefit__c.field-meta.xml
<CustomField>
    <fullName>cve__Benefit__c</fullName>
    <label>Benefit</label>
    <referenceTo>cve__Benefit__c</referenceTo>
    <relationshipLabel>Benefits Claimed</relationshipLabel>
    <relationshipName>BenefitClaimeds</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/cve__BenefitClaimed__c/fields/cve__Claim__c.field-meta.xml
<CustomField>
    <fullName>cve__Claim__c</fullName>
    <label>Claim</label>
    <referenceTo>cve__Claim__c</referenceTo>
    <relationshipLabel>Benefits Claimed</relationshipLabel>
    <relationshipName>BenefitClaimeds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/cve__BenefitClaimed__c/fields/cve__Status__c.field-meta.xml
<CustomField>
    <fullName>cve__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Appeal</fullName>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Approval Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cve__Claim__c/cve__Claim__c.object-meta.xml
<CustomObject>
    <customHelpPage>cve__ClaimHelp</customHelpPage>
    <label>Claim</label>
    <nameField>
        <displayFormat>C-{YYYY}-{000000}</displayFormat>
        <label>Claim Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cve__Claim__c/fields/cve__BenefitType__c.field-meta.xml
<CustomField>
    <fullName>cve__BenefitType__c</fullName>
    <label>Benefit Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cve__Claim__c/fields/cve__Status__c.field-meta.xml
<CustomField>
    <fullName>cve__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sanlam_Claim_Document__c/Sanlam_Claim_Document__c.object-meta.xml
<CustomObject>
    <description>Metadata table to map documents received and issued against a C Claim and BC Claim</description>
    <label>Documents</label>
    <nameField>
        <label>Claims Document Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sanlam_Claim_Document__c/fields/Benefit_Claimed__c.field-meta.xml
<CustomField>
    <fullName>Benefit_Claimed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Benefit Claimed</label>
    <referenceTo>cve__BenefitClaimed__c</referenceTo>
    <relationshipName>Benefit_Claimed</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sanlam_Claim_Document__c/fields/Claim_Number__c.field-meta.xml
<CustomField>
    <fullName>Claim_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim Number</label>
    <referenceTo>cve__Claim__c</referenceTo>
    <relationshipName>Claim_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sanlam_Claim_Document__c/fields/Document_ID__c.field-meta.xml
<CustomField>
    <fullName>Document_ID__c</fullName>
    <externalId>true</externalId>
    <label>Content Manager ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/RequiredDocumentTriggerHelperTest.cls
@isTest
private class RequiredDocumentTriggerHelperTest {
    @testSetup static void recquiredDocumentInsert(){
        cve__Claim__c  claimRecord = new   cve__Claim__c();  
        claimRecord.cve__BenefitType__c='Test';
        Insert claimRecord;
        cve__Product__c productRecord = new  cve__Product__c();
        productRecord.Name = 'Test';
        productRecord.cve__Status__c = 'Active';
        productRecord.cve_Sanlam_Product_ExternalID__c = 'xyz';
        productRecord.cve__Effective__c = date.Today()+30;
        Insert productRecord;
        cve__Benefit__c benefitRecord = new  cve__Benefit__c();
        benefitRecord.Name = 'Test';
        benefitRecord.cve__Effective__c = date.Today()+30;
        benefitRecord.Benefit_Code__c ='CSR55';
        benefitRecord.cve__Product__c = productRecord.Id;
        benefitRecord.cve__BenefitPercentage__c = 5.0;
        Insert benefitRecord ;
        cve__BenefitClaimed__c  bcRecord = new cve__BenefitClaimed__c();
        bcRecord.cve__Claim__c = claimRecord.Id;
        bcRecord.cve__Benefit__c = benefitRecord.Id;
        bcRecord.cve__Status__c = 'Pending';
        Insert bcRecord;
        Sanlam_Claim_Document__c  claimDocumentRecord = new  Sanlam_Claim_Document__c();
        claimDocumentRecord.Name = 'Test';
        claimDocumentRecord.Document_ID__c='xyz';
        claimDocumentRecord.Benefit_Claimed__c = bcRecord.Id;
        claimDocumentRecord.Claim_Number__c = claimRecord.Id;
        Insert claimDocumentRecord;
        Sanlam_Required_Documents__c requiredObj  = new  Sanlam_Required_Documents__c();
        requiredObj.Benefit_Claim__c = bcRecord.Id;
        requiredObj.Document_ID__c = claimDocumentRecord.Id;
        requiredObj.Name = 'Test';
        insert requiredObj;
    }
    testMethod static void testrequiredInsert()
    {
        List<cve__BenefitClaimed__c> benefitClaimedList   = [SELECT Id FROM cve__BenefitClaimed__c WHERE cve__Status__c = 'Pending'  Limit 1];
        List<Sanlam_Claim_Document__c> sanlamClaimDocumentList   = [SELECT Id FROM Sanlam_Claim_Document__c WHERE Name = 'Test' Limit 1];
        Sanlam_Required_Documents__c requiredObj  = new  Sanlam_Required_Documents__c();
        requiredObj.Benefit_Claim__c = benefitClaimedList[0].Id;
        requiredObj.Document_ID__c = sanlamClaimDocumentList[0].Id;
        requiredObj.Name = 'Test';
        requiredObj.Sanlam_Required__c = true;
        requiredObj.Sanlam_Document_Status__c = 'Received';
        test.startTest();
        insert requiredObj;
        test.stopTest();
    }
    testMethod static void testRequiredInsertRecord()
    {
        List<cve__BenefitClaimed__c> benefitClaimedList   = [SELECT Id FROM cve__BenefitClaimed__c WHERE cve__Status__c = 'Pending' Limit 1];
        List<Sanlam_Claim_Document__c> sanlamClaimDocumentList   = [SELECT Id FROM Sanlam_Claim_Document__c WHERE Name = 'Test' Limit 1];
        Sanlam_Required_Documents__c requiredObj  = new  Sanlam_Required_Documents__c();
        requiredObj.Benefit_Claim__c = benefitClaimedList[0].Id;
        requiredObj.Document_ID__c = sanlamClaimDocumentList[0].Id;
        requiredObj.Name = 'Test';
        requiredObj.Sanlam_Required__c = false;
        requiredObj.Sanlam_Document_Status__c = 'Received';
        test.startTest();
        insert requiredObj;
        system.assertEquals(benefitClaimedList!=null,True );
        test.stopTest();
    }
    
    testMethod static void recquiredDocumentUpdate()
    {
        List<Sanlam_Required_Documents__c>  sanlamRequiredDocumentsList = [SELECT Id, Name, Sanlam_Required__c, Sanlam_Document_Status__c FROM Sanlam_Required_Documents__c WHERE Name = 'Test'  Limit 1];
        sanlamRequiredDocumentsList[0].Sanlam_Required__c = false;
        sanlamRequiredDocumentsList[0].Sanlam_Document_Status__c = 'Received';
        test.startTest();
        update sanlamRequiredDocumentsList;
        system.assertEquals(sanlamRequiredDocumentsList!=null,True );
        test.stopTest();
    }
    
    
}